baseURL: "https://blog.neoqingyi.xyz"
title: "Neo çš„åšå®¢"
theme: "PaperMod"
languageCode: "zh-cn"
defaultContentLanguage: "zh"
pagination:
  pagerSize: 5  # æ¯é¡µ 5 ç¯‡æ–‡ç« 

outputs:
  home:
    - HTML
    - RSS
    - JSON  # ğŸ” æœç´¢åŠŸèƒ½ç”¨åˆ°

taxonomies:
  tag: "tags"
  category: "categories"

menu:
  main:
    - name: é¦–é¡µ
      url: /
      weight: 1
    - name: æ–‡ç« 
      url: /posts/
      weight: 2
    - name: æ ‡ç­¾
      url: /tags/
      weight: 3
    - name: å½’æ¡£
      url: /archives/
      weight: 4
    - name: æœç´¢
      url: /search/
      weight: 5

# config.yaml
params:
  comments: true  
  # 1. åˆ—è¡¨é¡µå…¨å±€éšè—å°é¢
  cover:
    hiddenInList: true   # åªå½±å“åˆ—è¡¨
  # 2. è¯¦æƒ…é¡µå…¨å±€å¯ç”¨å°é¢
  ShowCover: true        # åªå½±å“æ–‡ç« é¡µ
  defaultTheme: auto
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowWordCount: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowToc: true          # æ‰€æœ‰æ–‡ç« é»˜è®¤æ˜¾ç¤ºç›®å½•
  TocOpen: true         # é¡µé¢åŠ è½½æ—¶ç›®å½•æ˜¯å¦é»˜è®¤å±•å¼€ï¼ˆtrue=å±•å¼€ï¼‰
  tocWidth: 300          # ç›®å½•å®½åº¦ï¼ˆpxï¼‰
  homeInfoParams:
    Title: "ä½ å¥½ï¼Œæˆ‘æ˜¯ Neo ğŸ‘‹"
    Content: "10å¹´iOSå·¥ç¨‹å¸ˆï¼Œçƒ­çˆ±ç‹¬ç«‹å¼€å‘ä¸å†™ä½œã€‚è¿™ä¸ªåšå®¢è®°å½•æˆ‘æ¢ç´¢ AIã€è‡ªåŠ¨åŒ–ã€è‡ªç”±ç”Ÿæ´»çš„æ—…ç¨‹ã€‚"
  busuanzi:
    enable: true


  socialIcons:
    - name: github
      url: "https://github.com/yufanghui"
    - name: twitter
      url: "https://twitter.com/damenmatt06"